{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.selenus",
    "module": "iris-core",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "iris-core-1.1.0.jar",
          "url": "iris-core-1.1.0.jar",
          "size": 973358,
          "sha512": "a886f981da444f4847da657187043955998a9ebafab785be02cf914d0ea95c23c92affc7e20bd79163aa2e740ec1881e0cd35dfef0727e2cb337bf7907d00f55",
          "sha256": "8a66422d77eeb47147eb172752528cab5f55195e2b47d28f408c8eeef6cfecfc",
          "sha1": "320c88770b14ece899453fee9712e85e36891d63",
          "md5": "296601d2ed6e5663e8dfb5d06b4fc372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.78.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.78.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "4.32.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "iris-core-1.1.0.jar",
          "url": "iris-core-1.1.0.jar",
          "size": 973358,
          "sha512": "a886f981da444f4847da657187043955998a9ebafab785be02cf914d0ea95c23c92affc7e20bd79163aa2e740ec1881e0cd35dfef0727e2cb337bf7907d00f55",
          "sha256": "8a66422d77eeb47147eb172752528cab5f55195e2b47d28f408c8eeef6cfecfc",
          "sha1": "320c88770b14ece899453fee9712e85e36891d63",
          "md5": "296601d2ed6e5663e8dfb5d06b4fc372"
        }
      ]
    }
  ]
}
